<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FishingLogBook.Application\FishingLogBook.Application.csproj" />
    <ProjectReference Include="..\FishingLogBook.Domain\FishingLogBook.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FishingLogBook.Infrastructure</RootNamespace>
  </PropertyGroup>

</Project>
